fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    apache: https://github.com/puppetlabs/puppetlabs-apache.git
    firewall: https://github.com/puppetlabs/puppetlabs-firewall
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    selinux: https://github.com/voxpupuli/puppet-selinux.git
    systemd: https://github.com/voxpupuli/puppet-systemd.git
